# Generated by Django 3.1.3 on 2020-12-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='omAppraise',
            fields=[
                ('appraiseId', models.CharField(db_column='appraise_id', max_length=32, primary_key=True, serialize=False)),
                ('orderId', models.CharField(db_column='order_id', max_length=32, null=True, verbose_name='订单主键，外键')),
                ('vehicleRating', models.IntegerField(db_column='vehicle_rating', null=True, verbose_name='车辆评分')),
                ('cargoRating', models.IntegerField(db_column='cargo_rating', null=True, verbose_name='货物评分')),
                ('transporterRating', models.IntegerField(db_column='transporter_rating', null=True, verbose_name='托运人评分')),
                ('appraiseContent', models.CharField(db_column='appraise_content', max_length=320, null=True, verbose_name='评价内容')),
                ('companyId', models.CharField(db_column='company_id', max_length=32, null=True, verbose_name='公司ID')),
                ('deptId', models.CharField(db_column='dept_id', max_length=32, null=True, verbose_name='机构ID')),
                ('createUserId', models.CharField(db_column='create_user_id', max_length=32, null=True, verbose_name='创建人ID')),
                ('createTime', models.DateTimeField(db_column='create_time', max_length=6, null=True, verbose_name='创建时间')),
                ('updateUserId', models.CharField(db_column='update_user_id', max_length=32, null=True, verbose_name='更新人ID')),
                ('updateTime', models.DateTimeField(db_column='update_time', max_length=6, null=True, verbose_name='更新时间')),
                ('delFlag', models.IntegerField(db_column='del_flag', null=True, verbose_name='是否删除：1已删除，2未删除')),
            ],
            options={
                'db_table': 't_om_appraise',
            },
        ),
        migrations.CreateModel(
            name='omVehicleTrajectory',
            fields=[
                ('vehicleTrajectoryId', models.CharField(db_column='vehicle_trajectory_id', max_length=32, primary_key=True, serialize=False)),
                ('carId', models.CharField(db_column='car_id', max_length=32, null=True, verbose_name='车辆主键，外键')),
                ('orderId', models.CharField(db_column='order_id', max_length=32, null=True, verbose_name='订单主键，外键')),
                ('trajectoryTime', models.DateField(db_column='trajectory_time', max_length=6, null=True, verbose_name='车辆轨迹信息时间')),
                ('longitude', models.FloatField(db_column='longitude', null=True, verbose_name='经度')),
                ('latitude', models.FloatField(db_column='latitude', null=True, verbose_name='纬度')),
                ('companyId', models.CharField(db_column='company_id', max_length=32, null=True, verbose_name='公司ID')),
                ('deptId', models.CharField(db_column='dept_id', max_length=32, null=True, verbose_name='机构ID')),
                ('createUserId', models.CharField(db_column='create_user_id', max_length=32, null=True, verbose_name='创建人ID')),
                ('createTime', models.DateTimeField(db_column='create_time', max_length=6, null=True, verbose_name='创建时间')),
                ('updateUserId', models.CharField(db_column='update_user_id', max_length=32, null=True, verbose_name='更新人ID')),
                ('updateTime', models.DateTimeField(db_column='update_time', max_length=6, null=True, verbose_name='更新时间')),
                ('delFlag', models.IntegerField(db_column='del_flag', null=True, verbose_name='是否删除：1已删除，2未删除')),
            ],
            options={
                'db_table': 't_om_vehicle_trajectory',
            },
        ),
        migrations.AlterField(
            model_name='ombackorder',
            name='backOrderId',
            field=models.AutoField(db_column='back_order_id', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ombackorder',
            name='backOrderImagePath1',
            field=models.CharField(db_column='back_order_Image_path1', max_length=60, null=True, verbose_name='照片1'),
        ),
        migrations.AlterField(
            model_name='ombackorder',
            name='backOrderImagePath2',
            field=models.CharField(db_column='back_order_Image_path2', max_length=60, null=True, verbose_name='照片2'),
        ),
        migrations.AlterField(
            model_name='ombackorder',
            name='backOrderImagePath3',
            field=models.CharField(db_column='back_order_Image_path3', max_length=60, null=True, verbose_name='照片3'),
        ),
        migrations.AlterField(
            model_name='ombl',
            name='blId',
            field=models.AutoField(db_column='bl_id', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='omconcract',
            name='contractId',
            field=models.AutoField(db_column='contract_id', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='omdetail',
            name='detailId',
            field=models.AutoField(db_column='detail_id', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='omdetailwarehouse',
            name='warehouseId',
            field=models.AutoField(db_column='warehouse_id', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='omorder',
            name='orderId',
            field=models.AutoField(db_column='order_id', max_length=32, primary_key=True, serialize=False),
        ),
    ]
